/**
 * @file
 * @brief Declares the SensorData project message payload.
 * @details Included in the complete release 1.0.0 Doxygen reference.
 */

#pragma once

#include <cstdint>
#include <string_view>

namespace rtos::messages {

/** @brief Carries one simulated sensor sample to control subscribers. */
struct SensorData {
    /** Stable transport and diagnostics name. */
    static constexpr std::string_view name{"SensorData"};
    /** Default inter-process routing identifier. */
    static constexpr std::uint32_t defaultRoutingId{1001};
    /** Dimensionless sample value generated by the example sensor. */
    double value;
};

}  // namespace rtos::messages
